### ISSUE TITLE
Built-in support for Ethernet via USB?

### ISSUE THREAD

**Issue by nmoskopp** [LeToteTeam/kiosk_system_rpi3#21]
Hello,

would it be possible to support USB-to-Ethernet adapters out of the box for users who want to have an additional ethernet device on their Raspberry Pi? We could of course create a customized version of `kiosk_system_rpi3` *just* to set `CONFIG_USB_NET_AX88179_178A=y`, but it seems inefficient.

Greetings,
Nils Moskopp

**Comment by mobileoverlord** [comment]
We try to keep the common systems to a minimum amount of extra configs. Since the raspberry pi already has an ethernet port and I don't own one of the adapters you mentioned, its hard to test that between updates we don't break the other configs that were enabled. The strategy for now is to have users with custom modifications fork the system and tune it to their needs.
