### ISSUE TITLE
New version of the kiosk system for nerve 1.6?

### ISSUE THREAD

**Issue by epinault** [LeToteTeam/kiosk_system_rpi3#55]
Tried to update to nerves 1.6 but I got this error

Failed to use "nerves" (versions 1.6.0 and 1.6.1) because
  kiosk_system_rpi3 (version 1.9.1) requires ~> 1.5.0
  mix.exs specifies ~> 1.6

** (Mix) Hex dependency resolution failed, change the version requirements of your dependencies or unlock them (by using mix deps.update or mix deps.unlock). If you are unable to resolve the conflicts you can try overriding with {:dependency, "~> 1.0", override: true}

my current env:
OSX 10.15.4
Elixir 1.10.2-otp-22
Erlang 22.1.8

**Comment by fhunleth** [comment]
See PR #53. I don't know who maintains this repository now, so I'm not sure when/if it will be merged.

In the mean time, I suspect that marking `:nerves` to be `override: true` will work so that you can use 1.6.1. That's pretty painful for me to type, so I hope that someone can make a new `kiosk_system_rpi3` release. You could also force Nerves 1.5 and use Elixir 1.9.4.

**Comment by mobileoverlord** [comment]
This was pushed to hex in release v1.10.0
